# Generated by Django 5.2.17 on 2026-08-11 22:39

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_add_documentconversion"),
        # Depend on a wagtailcore migration present in all supported Wagtail
        # versions (6.3+), not the latest — this project is tested across a
        # version matrix, and referencing a newer migration breaks older ones.
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 4),
                            ("quote", 7),
                            ("code", 8),
                            ("table", 12),
                            ("list", 14),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [(1, "H1"), (2, "H2"), (3, "H3"), (4, "H4"), (5, "H5"), (6, "H6")]},
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("text", 0), ("level", 1)]], {}),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"template": "wagtail_pdf_converter/blocks/paragraph.html"},
                            ),
                            4: ("wagtail_pdf_converter.blocks.PDFImageBlock", (), {}),
                            5: ("wagtail.blocks.TextBlock", (), {}),
                            6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            7: ("wagtail.blocks.StructBlock", [[("text", 5), ("attribution", 6)]], {}),
                            8: ("wagtail.blocks.StructBlock", [[("code", 5), ("language", 6)]], {}),
                            9: ("wagtail.blocks.ListBlock", (0,), {"required": False}),
                            10: ("wagtail.blocks.ListBlock", (0,), {}),
                            11: ("wagtail.blocks.ListBlock", (10,), {"required": False}),
                            12: ("wagtail.blocks.StructBlock", [[("header", 9), ("rows", 11)]], {}),
                            13: ("wagtail.blocks.BooleanBlock", (), {"default": False, "required": False}),
                            14: ("wagtail.blocks.StructBlock", [[("ordered", 13), ("items", 10)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
