# Generated by Django 5.2.17 on 2026-08-11 15:46

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_add_documentconversion"),
        # Depend on a wagtailcore migration present in all supported Wagtail
        # versions (6.3+), not the latest — this project is tested across a
        # version matrix, and referencing a newer migration breaks older ones.
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("paragraph", 1)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
