# Generated by Django 5.2.17 on 2026-08-11 16:07

import wagtail.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_pdfpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("quote", 5),
                    ("code", 6),
                    ("table", 11),
                    ("list", 13),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: ("wagtail.blocks.StructBlock", [[("text", 3), ("attribution", 4)]], {}),
                    6: ("wagtail.blocks.StructBlock", [[("code", 3), ("language", 4)]], {}),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: ("wagtail.blocks.ListBlock", (7,), {"required": False}),
                    9: ("wagtail.blocks.ListBlock", (7,), {}),
                    10: ("wagtail.blocks.ListBlock", (9,), {"required": False}),
                    11: ("wagtail.blocks.StructBlock", [[("header", 8), ("rows", 10)]], {}),
                    12: ("wagtail.blocks.BooleanBlock", (), {"default": False, "required": False}),
                    13: ("wagtail.blocks.StructBlock", [[("ordered", 12), ("items", 9)]], {}),
                },
            ),
        ),
    ]
